/*------------------------------------------------------------------------------
-- 개체 이름: BIBIGO.TB_COMMON_CD
-- 만든 날짜: 2019-05-14 오후 1:42:51
-- 마지막 수정 날짜: 2019-05-14 오후 1:42:51
-- 상태: VALID
------------------------------------------------------------------------------*/
DROP TABLE BIBIGO.TB_COMMON_CD CASCADE CONSTRAINTS;

CREATE TABLE BIBIGO.TB_COMMON_CD (
  ID          NUMBER                 NOT NULL, 
  CODE_GB     VARCHAR2(100 BYTE)     NOT NULL, 
  CODE        VARCHAR2(100 BYTE)     NOT NULL, 
  CODE_VAL    VARCHAR2(500 BYTE)     NOT NULL, 
  ATTR1       VARCHAR2(100 BYTE)         NULL, 
  ATTR2       VARCHAR2(100 BYTE)         NULL, 
  ATTR3       VARCHAR2(100 BYTE)         NULL, 
  ATTR4       VARCHAR2(100 BYTE)         NULL, 
  ATTR5       VARCHAR2(100 BYTE)         NULL
)
TABLESPACE TS_BIBIGO
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE (
    INITIAL     64 K
    NEXT        1 M
    MINEXTENTS  1
    MAXEXTENTS  UNLIMITED
)
LOGGING
NOCACHE
MONITORING
NOPARALLEL
;

COMMENT ON TABLE BIBIGO.TB_COMMON_CD IS '공통 코드 테이블';

COMMENT ON COLUMN BIBIGO.TB_COMMON_CD.ID IS '코드 ID';

COMMENT ON COLUMN BIBIGO.TB_COMMON_CD.CODE_GB IS '코드 구분';

COMMENT ON COLUMN BIBIGO.TB_COMMON_CD.CODE IS '코드';

COMMENT ON COLUMN BIBIGO.TB_COMMON_CD.CODE_VAL IS '코드값';

COMMENT ON COLUMN BIBIGO.TB_COMMON_CD.ATTR1 IS '속성 1';

COMMENT ON COLUMN BIBIGO.TB_COMMON_CD.ATTR2 IS '속성 2';

COMMENT ON COLUMN BIBIGO.TB_COMMON_CD.ATTR3 IS '속성 3';

COMMENT ON COLUMN BIBIGO.TB_COMMON_CD.ATTR4 IS '속성 4';

COMMENT ON COLUMN BIBIGO.TB_COMMON_CD.ATTR5 IS '속성 5';

/*------------------------------------------------------------------------------
-- 개체 이름: BIBIGO.TB_PARKING_INFO
-- 만든 날짜: 2019-05-14 오후 1:42:58
-- 마지막 수정 날짜: 2019-05-14 오후 1:42:58
-- 상태: VALID
------------------------------------------------------------------------------*/
DROP TABLE BIBIGO.TB_PARKING_INFO CASCADE CONSTRAINTS;

CREATE TABLE BIBIGO.TB_PARKING_INFO (
  ID           NUMBER                NOT NULL, 
  LAT          FLOAT(22)             NOT NULL, 
  LNG          FLOAT(22)             NOT NULL, 
  CITY         VARCHAR2(20 BYTE)         NULL, 
  DISTRICT     VARCHAR2(20 BYTE)         NULL, 
  CAR_ID       VARCHAR2(20 BYTE)     NOT NULL, 
  PARK_DATE    DATE                  NOT NULL, 
  IMAGE        BLOB                      NULL
)
LOB (IMAGE) STORE AS (
    TABLESPACE TS_BIBIGO
    ENABLE STORAGE IN ROW
    CHUNK 8192
    NOCACHE
    LOGGING
    STORAGE (
        INITIAL     64 K
        NEXT        1 M
        MINEXTENTS  1
        MAXEXTENTS  UNLIMITED
    )
)
TABLESPACE TS_BIBIGO
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE (
    INITIAL     64 K
    NEXT        1 M
    MINEXTENTS  1
    MAXEXTENTS  UNLIMITED
)
LOGGING
NOCACHE
MONITORING
NOPARALLEL
;

COMMENT ON TABLE BIBIGO.TB_PARKING_INFO IS '불법 주차 정보 테이블';

COMMENT ON COLUMN BIBIGO.TB_PARKING_INFO.ID IS 'ID';

COMMENT ON COLUMN BIBIGO.TB_PARKING_INFO.LAT IS '위도';

COMMENT ON COLUMN BIBIGO.TB_PARKING_INFO.LNG IS '경도';

COMMENT ON COLUMN BIBIGO.TB_PARKING_INFO.CITY IS '시';

COMMENT ON COLUMN BIBIGO.TB_PARKING_INFO.DISTRICT IS '구';

COMMENT ON COLUMN BIBIGO.TB_PARKING_INFO.CAR_ID IS '차량 번호';

COMMENT ON COLUMN BIBIGO.TB_PARKING_INFO.PARK_DATE IS '일시';

COMMENT ON COLUMN BIBIGO.TB_PARKING_INFO.IMAGE IS '캡쳐화면';


/*------------------------------------------------------------------------------
-- 개체 이름: BIBIGO.TB_USER
-- 만든 날짜: 2019-05-14 오후 1:43:06
-- 마지막 수정 날짜: 2019-05-14 오후 1:43:06
-- 상태: VALID
------------------------------------------------------------------------------*/
DROP TABLE BIBIGO.TB_USER CASCADE CONSTRAINTS;

CREATE TABLE BIBIGO.TB_USER (
  PASSWORD    VARCHAR2(400 BYTE)     NOT NULL
)
TABLESPACE TS_BIBIGO
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE (
    INITIAL     64 K
    NEXT        1 M
    MINEXTENTS  1
    MAXEXTENTS  UNLIMITED
)
LOGGING
NOCACHE
MONITORING
NOPARALLEL
;

COMMENT ON TABLE BIBIGO.TB_USER IS '사용자 정보 테이블';

COMMENT ON COLUMN BIBIGO.TB_USER.PASSWORD IS '비밀번호';

